# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CodersCamp2021 |  Breaking Bad Game - JavaScript CI

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: 'Build Breaking Bad Game application'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:ci
      - uses: actions/upload-artifact@v1
        name: Upload build as artifact
        with:
          name: breaking-bad-dist
          path: ./dist
      - name: Upload test coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: javascript-project-breaking-bad
